### ISSUE TITLE
Bug: Switch has invalid visual state

### ISSUE THREAD

**Issue by flomSStaar** [roninoss/rn-primitives#29]
# Issue: Switch does not display the correct visual state on the second toggle

## Description:

I've encountered a problem with the Switch component where the visual state doesn't update correctly. Here are the steps to reproduce the issue:

1. The Switch starts in an initial state (e.g., off).
2. On the first toggle, the Switch correctly updates its visual state (e.g., on).
3. On the second toggle, the visual state of the Switch does not update correctly and remains in the previous state.
4. From this point onward, the visual state of the Switch is inverted compared to its actual logical state.

## Environment

- Native version
- @rn-primitives/switch: 1.0.3

## Visual Example:

I have attached a video that clearly demonstrates the issue. You can see that the visual and logical states are out of sync after the second toggle.

https://github.com/user-attachments/assets/56271cf7-5413-4d6d-bc9e-e86258b01257

## Possible solutions

It seems that there is an issue with the animated style in the `SwitchNative` component, specifically with the `interpolateColor` function for changing the backgroundColor value.

**Comment by mrzachnugent** [comment]
@flomSStaar this looks like an issue that was solved last week in react-native-reusables https://github.com/mrzachnugent/react-native-reusables/commit/d9c3423f808d823ecf596446bb412ecb07e89344

**Comment by flomSStaar** [comment]
Thanks for your reply, it turns out that the sample project containing the Switch component has not been updated and still contains the old version of the code. That's why when running the sample project, the bug was still present.
